// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsjspeowlytshyxipvzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzanNwZW93bHl0c2h5eGlwdnp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODgxMDAsImV4cCI6MjA2NjY2NDEwMH0.ZGHtWe3lvFF9MjVHW7CsWdeVoqCfQUikb6WkJMPqYxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);